include /etc/openldap/schema/core.schema
include /etc/openldap/schema/cosine.schema
include /etc/openldap/schema/inetorgperson.schema

pidfile /run/openldap/slapd.pid
argsfile /run/openldap/slapd.args
modulepath /usr/lib/openldap
moduleload back_mdb.so

TLSCertificateFile /certs/tls.crt
TLSCertificateKeyFile /certs/tls.key
TLSCACertificateFile /certs/ca.crt
TLSVerifyClient never

database mdb
maxsize 67108864
suffix "dc=idpam,dc=test"
rootdn "cn=admin,dc=idpam,dc=test"
rootpw {SSHA}ZfAu1oykL+DA21IWFv9uK8q4IV8LrG/G
directory /var/lib/openldap/openldap-data
index objectClass eq
index uid,mail eq

access to attrs=userPassword
  by self write
  by anonymous auth
  by dn.exact="cn=readonly,dc=idpam,dc=test" read
  by * none

access to *
  by dn.exact="cn=readonly,dc=idpam,dc=test" read
  by self read
  by * none
